server:
  port: 9100
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    password: postgres
    platform: postgres
   #url: jdbc:postgresql://host.docker.internal:5432/faculty #docker
    url: jdbc:postgresql://localhost:5432/faculty
    username: postgres
  jackson:
    serialization:
      fail-on-empty-beans: false
  cloud:
    config:
      override-none: true
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
eureka:
    client:
      serviceUrl:
         #defaultZone: http://netflix-eureka:8763/eureka #docker
          defaultZone: http://localhost:8763/eureka

