server:
  port: 9200
eureka:
    client:
      serviceUrl:
         #defaultZone: http://netflix-eureka:8761/eureka #docker
          defaultZone: http://localhost:8763/eureka
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    password: servicedb123
    platform: postgres
   #url: jdbc:postgresql://host.docker.internal:5432/faculty #docker
    url: jdbc:postgresql://servicedb.cmiwljpzwpm2.eu-west-1.rds.amazonaws.com:5432/faculty
    username: postgres