eureka:
  client:
    serviceUrl:
      # defaultZone: http://netflix-eureka:8763/eureka #docker
      defaultZone: http://localhost:8763/eureka
server:
  port: 8765
spring:
  application:
    name: zuul
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 
    