eureka:
  client:
    serviceUrl:
      # defaultZone: http://netflix-eureka:8763/eureka #docker
      defaultZone: http://localhost:8763/eureka
server:
  port: 8765
spring:
  application:
    name: zuul